name: Bug
description: Report an issue to help improve the project.
title: 'Bug: '
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue. Please include what you tried and what didn't work.
    validations:
      required: true
  - type: textarea
    id: visual_proof
    attributes:
      label: Screenshots / Screen Recordings
      description: |
        Please drag and drop screenshots or screen recordings (videos) here. 
        Video is highly recommended for UI glitches or animation issues.
    validations:
      required: false