name: General Feature Request
description: Have a new idea/feature? Please suggest!
title: 'Feature: '
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose. Also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: visual_proof
    attributes:
      label: Screenshots / Mockups / Videos
      description: |
        Drag and drop any visuals (screenshots, video examples, mockups) that help explain your idea.
    validations:
      required: false